import React, { useState } from 'react';
import { useProject } from '../context/ProjectContext';
import { Department } from '../types';
import { getStorage, ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { FileText, Upload, Calendar, Download, Trash2, Eye } from 'lucide-react';

const STORAGE_BUCKET = 'callsheets';

export const CallSheetView: React.FC = () => {
    const { user, currentDept, callSheets, addCallSheet, t } = useProject();
    const [isUploading, setIsUploading] = useState(false);
    const [uploadDate, setUploadDate] = useState(new Date().toISOString().split('T')[0]);
    const [uploadName, setUploadName] = useState('');
    const [file, setFile] = useState<File | null>(null);
    const [error, setError] = useState<string | null>(null);

    const canUpload = user?.department === 'PRODUCTION' || user?.department === Department.MISE_EN_SCENE;

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const selectedFile = e.target.files[0];
            if (selectedFile.type !== 'application/pdf') {
                setError('Seuls les fichiers PDF sont acceptés.');
                return;
            }
            if (selectedFile.size > 10 * 1024 * 1024) { // 10MB limit
                setError('Le fichier est trop volumineux (max 10Mo).');
                return;
            }
            setFile(selectedFile);
            setError(null);

            // Auto-fill name if empty
            if (!uploadName) {
                // Remove extension and clean up
                const cleanName = selectedFile.name.replace('.pdf', '').replace(/[-_]/g, ' ');
                setUploadName(cleanName);
            }
        }
    };

    const handleUpload = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!file || !uploadName || !uploadDate) return;

        setIsUploading(true);
        setError(null);

        try {
            // 1. Upload to Firebase Storage
            // Use storage from firebase.ts to ensure correct initialization
            // const storage = getStorage(); // OLD
            const { storage } = await import('../services/firebase');

            // Organize by Project ID if possible, but context doesn't give clean project ID directly safely without checking
            const storageRef = ref(storage, `callsheets/${Date.now()}_${file.name}`);

            // Add metadata
            const metadata = {
                customMetadata: {
                    uploadedBy: user?.name || 'Unknown',
                    department: user?.department || 'Unknown'
                }
            };

            // Race against a timeout to detect hangs (common with permission issues)
            const uploadTask = uploadBytes(storageRef, file, metadata);
            const timeoutPromise = new Promise((_, reject) =>
                setTimeout(() => reject(new Error("Délai d'attente dépassé (15s). Vérifiez votre connexion ou les permissions.")), 15000)
            );

            await Promise.race([uploadTask, timeoutPromise]);

            const downloadUrl = await getDownloadURL(storageRef);

            // 2. Add to Firestore via Context
            await addCallSheet({
                id: '', // Generated by Firestore
                date: uploadDate,
                uploadDate: new Date().toISOString(),
                name: uploadName,
                url: downloadUrl,
                uploadedBy: user?.name || 'Inconnu',
                department: user?.department as (Department | 'PRODUCTION')
            });

            // Reset Form
            setFile(null);
            setUploadName('');
            setIsUploading(false);
        } catch (err: any) {
            console.error("Upload failed", err);
            let msg = "Échec du téléchargement.";
            if (err.message.includes("permission")) msg = "Erreur de permission (Storage).";
            if (err.message.includes("Délai")) msg = err.message;
            if (err.code === 'storage/unauthorized') msg = "Non autorisé à envoyer des fichiers.";

            setError(`${msg} (${err.code || err.message})`);
            setIsUploading(false);
        }
    };

    return (
        <div className="space-y-6 pb-20">
            {/* Header */}
            <div className="flex justify-between items-center bg-white p-4 rounded-xl shadow-sm border border-stone-200/60">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-stone-100 rounded-lg">
                        <FileText className="w-5 h-5 text-stone-600" />
                    </div>
                    <div>
                        <h2 className="text-lg font-bold text-stone-800">Feuilles de Service</h2>
                        <p className="text-sm text-stone-500">Consultez et téléchargez les feuilles de service</p>
                    </div>
                </div>
            </div>

            {/* Upload Section (Restricted) */}
            {canUpload && (
                <div className="bg-white p-6 rounded-xl shadow-sm border border-stone-200/60">
                    <h3 className="text-md font-semibold text-stone-800 mb-4 flex items-center gap-2">
                        <Upload className="w-4 h-4" /> Ajouter une feuille de service
                    </h3>

                    <form onSubmit={handleUpload} className="space-y-4">
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div>
                                <label className="block text-xs font-medium text-stone-500 mb-1">Date de la feuille</label>
                                <input
                                    type="date"
                                    required
                                    value={uploadDate}
                                    onChange={(e) => setUploadDate(e.target.value)}
                                    className="w-full px-3 py-2 rounded-lg bg-stone-50 border border-stone-200 focus:outline-none focus:ring-2 focus:ring-stone-400"
                                />
                            </div>
                            <div className="md:col-span-2">
                                <label className="block text-xs font-medium text-stone-500 mb-1">Nom (ex: J12 - Décor Appartement)</label>
                                <input
                                    type="text"
                                    required
                                    placeholder="Nom de la feuille de service"
                                    value={uploadName}
                                    onChange={(e) => setUploadName(e.target.value)}
                                    className="w-full px-3 py-2 rounded-lg bg-stone-50 border border-stone-200 focus:outline-none focus:ring-2 focus:ring-stone-400"
                                />
                            </div>
                        </div>

                        <div>
                            <label className="block text-xs font-medium text-stone-500 mb-1">Fichier PDF</label>
                            <div className="flex items-center gap-4">
                                <input
                                    type="file"
                                    accept=".pdf"
                                    onChange={handleFileChange}
                                    className="block w-full text-sm text-stone-500
                                    file:mr-4 file:py-2 file:px-4
                                    file:rounded-full file:border-0
                                    file:text-sm file:font-semibold
                                    file:bg-stone-100 file:text-stone-700
                                    hover:file:bg-stone-200
                                    cursor-pointer"
                                />
                                {file && (
                                    <span className="text-xs text-green-600 font-medium whitespace-nowrap">
                                        {(file.size / 1024 / 1024).toFixed(2)} Mo
                                    </span>
                                )}
                            </div>
                        </div>

                        {error && (
                            <div className="p-3 bg-red-50 text-red-600 text-sm rounded-lg">
                                {error}
                            </div>
                        )}

                        <div className="flex justify-end">
                            <button
                                type="submit"
                                disabled={!file || isUploading}
                                className={`px-6 py-2 rounded-xl text-white font-medium shadow-sm transition-all
                                    ${!file || isUploading
                                        ? 'bg-stone-300 cursor-not-allowed'
                                        : 'bg-stone-800 hover:bg-stone-900 shadow-md hover:shadow-lg'
                                    }`}
                            >
                                {isUploading ? 'Envoi en cours...' : 'Publier la feuille'}
                            </button>
                        </div>
                    </form>
                </div>
            )}

            {/* List */}
            <div className="space-y-3">
                {callSheets.length === 0 ? (
                    <div className="text-center py-12 bg-stone-50 rounded-xl border border-stone-100">
                        <FileText className="w-12 h-12 text-stone-300 mx-auto mb-3" />
                        <p className="text-stone-500">Aucune feuille de service disponible pour le moment.</p>
                    </div>
                ) : (
                    callSheets.map((sheet) => (
                        <div key={sheet.id} className="bg-white p-4 rounded-xl border border-stone-200 shadow-sm hover:shadow-md transition-shadow flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                            <div className="flex items-start gap-4">
                                <div className="p-3 bg-red-50 text-red-600 rounded-xl">
                                    <FileText className="w-6 h-6" />
                                </div>
                                <div>
                                    <div className="flex items-center gap-2 mb-1">
                                        <h3 className="font-semibold text-stone-800">{sheet.name}</h3>
                                        <span className="text-xs px-2 py-0.5 bg-stone-100 text-stone-600 rounded-full border border-stone-200">
                                            {new Date(sheet.date).toLocaleDateString()}
                                        </span>
                                        {/* New Badge if recent (e.g. uploaded today) */}
                                        {new Date(sheet.uploadDate).toDateString() === new Date().toDateString() && (
                                            <span className="text-[10px] px-1.5 py-0.5 bg-red-100 text-red-600 rounded-full font-bold">
                                                NOUVEAU
                                            </span>
                                        )}
                                    </div>
                                    <p className="text-xs text-stone-500">
                                        Mise en ligne par {sheet.uploadedBy} le {new Date(sheet.uploadDate).toLocaleDateString()} à {new Date(sheet.uploadDate).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                    </p>
                                </div>
                            </div>

                            <div className="flex gap-2 w-full sm:w-auto">
                                <a
                                    href={sheet.url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-2 bg-stone-100 text-stone-700 rounded-lg hover:bg-stone-200 transition-colors text-sm font-medium"
                                >
                                    <Eye className="w-4 h-4" />
                                    Voir
                                </a>
                                <a
                                    href={sheet.url}
                                    download // Note: download attribute often ignored for cross-origin, but good intent
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-2 bg-stone-800 text-white rounded-lg hover:bg-stone-900 transition-colors text-sm font-medium"
                                >
                                    <Download className="w-4 h-4" />
                                    Télécharger
                                </a>
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
};
